# Generated by Django 3.0 on 2020-02-17 09:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Hospital_Name', models.CharField(max_length=254)),
                ('Hospital_Location', models.TextField(max_length=1000)),
                ('Hospital_Contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format', regex='((\\+*)((0[ -]+)*|(91 )*)(\\d{12}+|\\d{10}+))|\\d{5}([- ]*)\\d{6}$')])),
                ('Hospital_Logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Email', models.EmailField(max_length=254)),
                ('User_Password', models.CharField(max_length=100)),
                ('User_BirthDate', models.DateField()),
                ('User_BloodGroup', models.CharField(max_length=4)),
                ('User_Icon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('Doctors_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Doctors_Name', models.CharField(max_length=254)),
                ('Doctors_Specialisation', models.CharField(choices=[(' Allergist', ' Allergist'), (' Anesthesiologist', ' Anesthesiologist'), (' Cardiologist', 'Cardiologist '), (' Orthopaedic', ' Orthopaedic'), (' Endocrinologist', ' Endocrinologist'), (' Dermatologist', ' Dermatologist')], max_length=200)),
                ('Doctors_Icon', models.CharField(max_length=1000)),
                ('Doctors_Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.Hospital')),
            ],
        ),
    ]
