# Generated by Django 3.0 on 2020-02-19 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Svasth', '0003_auto_20200219_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_Date',
            field=models.DateField(default=datetime.date(2020, 2, 19)),
        ),
    ]
