# Generated by Django 3.0 on 2020-02-20 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Svasth', '0005_auto_20200219_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Report_Name', models.CharField(choices=[(' CT Scan ', ' CT Scan '), (' Blood Report ', ' Blood Report '), (' ECG ', ' ECG '), (' Urine Report ', ' Urine Report ')], max_length=200)),
                ('Report_Desc', models.CharField(blank=True, default='', max_length=500)),
                ('Report_Date', models.DateField(default=django.utils.timezone.now)),
                ('Report_file', models.FileField(upload_to='')),
                ('Report_Doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.Doctor')),
                ('Report_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.User')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTime',
            fields=[
                ('LoginTime_Id', models.AutoField(primary_key=True, serialize=False)),
                ('LoginTime_DateTime', models.DateTimeField(auto_now_add=True)),
                ('LoginTime_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.User')),
            ],
        ),
    ]
