# Generated by Django 3.0.3 on 2020-02-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Svasth', '0007_auto_20200220_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_Date', models.DateField()),
                ('Appointment_Time', models.TimeField()),
                ('Appointment_Doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.Doctor')),
                ('Appointment_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.User')),
            ],
        ),
    ]
