# Generated by Django 3.0.3 on 2020-03-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Svasth', '0010_auto_20200221_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintime',
            name='LoginTime_DateTime',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('Relationships_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Relationships_Date', models.DateField()),
                ('Relationships_Doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.Doctor')),
                ('Relationships_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Svasth.User')),
            ],
        ),
    ]
