# Generated by Django 3.0.3 on 2020-03-06 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Svasth', '0012_auto_20200306_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationships',
            new_name='Relationship',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Contact_DateTime', models.DateTimeField()),
                ('Contact_Name', models.CharField(max_length=255)),
                ('Contact_Email', models.EmailField(max_length=254)),
                ('Contact_Message', models.TextField(max_length=1000)),
                ('Contact_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Svasth.User')),
            ],
        ),
    ]
