# Generated by Django 2.2.1 on 2020-03-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Svasth', '0013_auto_20200306_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Report_Name',
            field=models.CharField(choices=[(' CT Scan ', ' CT Scan '), (' Blood Report ', ' Blood Report '), (' ECG ', ' ECG '), (' Urine Report ', ' Urine Report '), (' X-Ray Report ', ' X-Ray Report '), (' UltraSound Report ', ' UltraSound Report ')], max_length=200),
        ),
    ]
